version: 2

models:
  - name: lego
    columns:
      - name: theme_name # replace with actual column name
        data_tests:
          - not_null
      - name: set_name # replace with actual column name
        data_tests:
          - not_null
      - name: set_year # replace with actual column name
        data_tests:
          - not_null          